```mermaid

architecture-beta
    group awsCloud(cloud)[AWS Cloud]
    service cf(internet)[CloudFront] in awsCloud
    service s3(database)[S3 Bucket] in awsCloud
    service cjpc(internet)[CJ IP] in awsCloud

    group vpc(cloud)[VPC] in awsCloud

    group public(cloud)[Public Subnet] in vpc
    service lb(server)[LoadBalancer] in public
    service bastion(server)[CJ Bastion] in public

    group private(cloud)[Private Subnet] in vpc
    service db(database)[Database] in private
    service fg(disk)[Fargete EC2 Instance] in private

    cf:B --> L:lb
    cf:R --> L:s3
    lb:R --> L:fg
    fg:B --> T:db
    cjpc:R --> L:bastion
    bastion:R --> L:db

```